package s3domain

// Update
type JsonFile struct {
	Result  *int    `json:"result,omitempty"`
	Message *string `json:"message,omitempty"`
	Data    struct {
		Inv struct {
			ID                  *int    `json:"id,omitempty"`
			LogID               *int    `json:"log_id,omitempty"`
			MoveID              *int    `json:"move_id,omitempty"`
			ExitID              *int    `json:"exit_id,omitempty"`
			LogInv              *int    `json:"log_inv,omitempty"`
			Title               *string `json:"title,omitempty"`
			Invoice             *string `json:"invoice,omitempty"`
			InvType             *string `json:"inv_type,omitempty"`
			LogDate             *string `json:"log_date,omitempty"`
			LogUpdated          *string `json:"log_updated,omitempty"`
			ExitDate            *string `json:"exit_date,omitempty"`
			ExitUpdated         *string `json:"exit_updated,omitempty"`
			ExitTitle           *string `json:"exit_title,omitempty"`
			ExitType            *string `json:"exit_type,omitempty"`
			ExitRate            *string `json:"exit_rate,omitempty"`
			ExitAwb             *string `json:"exit_awb,omitempty"`
			MoveAwb             *string `json:"move_awb,omitempty"`
			Created             *string `json:"created,omitempty"`
			Updated             *string `json:"updated,omitempty"`
			Warehouse           *string `json:"warehouse,omitempty"`
			Message             *string `json:"message,omitempty"`
			Type                *string `json:"type,omitempty"`
			Status              *string `json:"status,omitempty"`
			Attachment          *string `json:"attachment,omitempty"`
			Detail              *string `json:"detail,omitempty"`
			Seller              *string `json:"seller,omitempty"`
			SellerName          *string `json:"seller_name,omitempty"`
			SenderName          *string `json:"sender_name,omitempty"`
			SenderPhone         *string `json:"sender_phone,omitempty"`
			SenderPhoto         *string `json:"sender_photo,omitempty"`
			ReceiverName        *string `json:"receiver_name,omitempty"`
			ReceiverAddr        *string `json:"receiver_addr,omitempty"`
			ReceiverPhone       *string `json:"receiver_phone,omitempty"`
			ReceiverEmail       *string `json:"receiver_email,omitempty"`
			ReceiverLatlon      *string `json:"receiver_latlon,omitempty"`
			Info                *string `json:"info,omitempty"`
			Info1               *string `json:"info1,omitempty"`
			Info2               *string `json:"info2,omitempty"`
			Info3               *string `json:"info3, omitempty,omitempty"`
			PickupType          *string `json:"pickup_type,omitempty"`
			PickupStatus        *string `json:"pickup_status,omitempty"`
			ReturnStatus        *string `json:"return_status,omitempty"`
			TransactionVal      *int    `json:"transaction_val,omitempty"`
			Fee                 *int    `json:"fee,omitempty"`
			FeeWarehouse        *int    `json:"fee_warehouse,omitempty"`
			BookingCode         *string `json:"booking_code,omitempty"`
			StorageType         *string `json:"storage_type,omitempty"`
			ShowLogo            *string `json:"show_logo,omitempty"`
			PackagingVal        *int    `json:"packaging_val,omitempty"`
			PackagingSubs       *int    `json:"packaging_subs,omitempty"`
			EstimateShippingFee *int    `json:"estimate_shipping_fee,omitempty"`
			ShippingFee         *int    `json:"shipping_fee,omitempty"`
			Vehicle             *string `json:"vehicle,omitempty"`
			PerformanceTime     *int    `json:"performance_time,omitempty"`
			PerformanceCounting *string `json:"performance_counting,omitempty"` // typo perbaiki nama json menjadi `performance_counting``
			IsLock              *string `json:"is_lock,omitempty"`
			IsPaid              *string `json:"is_paid,omitempty"`
			Marketplace         *string `json:"marketplace,omitempty"`
			Skema               *string `json:"skema,omitempty"`
			TotalSku            *int    `json:"total_sku,omitempty"`
			TotalStock          *int    `json:"total_stock,omitempty"`
			Rate                *string `json:"rate,omitempty"`
			InvRate             *string `json:"inv_rate,omitempty"`
			LogisticType        *string `json:"logistic_type,omitempty"`
			Barcode             *string `json:"barcode,omitempty"`
			MarketplaceName     *string `json:"marketplace_name,omitempty"`
			Platform            *string `json:"platform,omitempty"`
			PickingTs           *string `json:"picking_ts,omitempty"`
			PackingTs           *string `json:"packing_ts,omitempty"`
			ShippingTs          *string `json:"shipping_ts,omitempty"`
			DoneTs              *string `json:"done_ts,omitempty"`
			IntervalAwb         *int    `json:"interval_awb,omitempty"`
			Awb                 *string `json:"awb,omitempty"`
			LogAwb              *string `json:"log_awb,omitempty"`
			OldInv              *int    `json:"old_inv,omitempty"`
			From                *string `json:"from,omitempty"`
			To                  *string `json:"to,omitempty"`
			VoucherID           *int    `json:"voucher_id,omitempty"`
			Voucher             *struct {
				ID            *int    `json:"id,omitempty"`
				Created       *string `json:"created,omitempty"`
				CreatedBy     *string `json:"created_by,omitempty"`
				Vcode         *string `json:"vcode,omitempty"`
				Nominal       *int    `json:"nominal,omitempty"`
				From          *string `json:"from,omitempty"`
				To            *string `json:"to,omitempty"`
				Target        *string `json:"target,omitempty"`
				RedeemBy      *string `json:"redeem_by,omitempty"`
				RedeemDate    *string `json:"redeem_date,omitempty"`
				Type          *string `json:"type,omitempty"`
				Vsource       *string `json:"vsource,omitempty"`
				TransactionID *int    `json:"transaction_id,omitempty"`
			} `json:"voucher,omitempty"`
			Packets []*struct {
				ID          *int    `json:"id,omitempty"`
				Seller      *string `json:"seller,omitempty"`
				LogID       *int    `json:"log_id,omitempty"`
				Title       *string `json:"title,omitempty"`
				Status      *string `json:"status,omitempty"`
				ArrivedTime *string `json:"arrived_time,omitempty"`
				Resi        *string `json:"resi,omitempty"`
				Items       []*struct {
					ID         *int    `json:"id,omitempty"`
					DropshipID *int    `json:"dropship_id,omitempty"`
					Name       *string `json:"name,omitempty"`
					Qty        *int    `json:"qty,omitempty"`
				} `json:"items,omitempty"`
			} `json:"packets,omitempty"`
			Exchanged *struct {
				ID    *string `json:"id,omitempty"`
				Type  *string `json:"type,omitempty"`
				Title *string `json:"title,omitempty"`
			} `json:"exchanged,omitempty"`
			DetailFrom *struct {
				ID        *int    `json:"id,omitempty"`
				Name      *string `json:"name,omitempty"`
				Photo     *string `json:"photo,omitempty"`
				Kecamatan *string `json:"kecamatan,omitempty"`
				Kelurahan *string `json:"kelurahan,omitempty"`
				City      *string `json:"city,omitempty"`
			} `json:"detail_from,omitempty"`
			DetailTo *struct {
				ID        *int    `json:"id,omitempty"`
				Name      *string `json:"name,omitempty"`
				Photo     *string `json:"photo,omitempty"`
				Kecamatan *string `json:"kecamatan,omitempty"`
				Kelurahan *string `json:"kelurahan,omitempty"`
				City      *string `json:"city,omitempty"`
			} `json:"detail_to,omitempty"`
			Logistic *struct {
				ID          *int    `json:"id,omitempty"`
				Name        *string `json:"name,omitempty"`
				Icon        *string `json:"icon,omitempty"`
				Type        *string `json:"type,omitempty"`
				Active      *string `json:"active,omitempty"`
				Cashless    *string `json:"cashless,omitempty"`
				BookingType *string `json:"booking_type,omitempty"`
				PickupType  *string `json:"pickup_type,omitempty"`
				Company     *string `json:"company,omitempty"`
			} `json:"logistic,omitempty"`
			Packaging []*struct {
				PackagingID         *int    `json:"packaging_id,omitempty"`
				PackagingName       *string `json:"packaging_name,omitempty"`
				PackagingUnit       *string `json:"packaging_unit,omitempty"`
				PackagingPrice      *int    `json:"packaging_price,omitempty"`
				PackagingImage      *string `json:"packaging_image,omitempty"`
				PackagingImageThumb *string `json:"packaging_image_thumb,omitempty"`
				Qty                 *int    `json:"qty,omitempty"`
				Total               *int    `json:"total,omitempty"`
			} `json:"packaging,omitempty"`
			Items []*struct {
				ID               *int    `json:"id,omitempty"`
				Sku              *int    `json:"sku,omitempty"`
				Seller           *string `json:"seller,omitempty"`
				SellerName       *string `json:"seller_name,omitempty"`
				ProductID        *int    `json:"product_id,omitempty"`
				SkuID            *int    `json:"sku_id,omitempty"`
				SkuLabel         *string `json:"sku_label,omitempty"`
				Name             *string `json:"name,omitempty"`
				Qty              *int    `json:"qty,omitempty"`
				Price            *int    `json:"price,omitempty"`
				Picture          *string `json:"picture,omitempty"`
				PictureThumb     *string `json:"picture_thumb,omitempty"`
				Qc               *string `json:"qc,omitempty"`
				QcFlag           *int    `json:"qc_flag,omitempty"`
				QcStatus         *string `json:"qc_status,omitempty"`
				QcPass           *string `json:"qc_pass,omitempty"`
				ExpiredFlag      *string `json:"expired_flag,omitempty"`
				VariantFirstLvl  *int    `json:"variant_first_lvl,omitempty"`
				VariantSecondLvl *int    `json:"variant_second_lvl,omitempty"`
				BinPicked        []*struct {
					BinID *string `json:"bin_id,omitempty"`
					Qty   *string `json:"qty,omitempty"`
					Name  *string `json:"name,omitempty"`
				} `json:"bin_picked,omitempty"`
				Packages []*struct {
					ID         *int    `json:"id,omitempty"`
					Name       *string `json:"name,omitempty"`
					Unit       *string `json:"unit,omitempty"`
					Price      *int    `json:"price,omitempty"`
					Image      *string `json:"image,omitempty"`
					ImageThumb *string `json:"image_thumb,omitempty"`
					Qty        *int    `json:"qty,omitempty"`
					Total      *int    `json:"total,omitempty"`
				}
			} `json:"items,omitempty"`
		} `json:"inv,omitempty"`
		Awb *struct {
			ID          *int    `json:"id,omitempty"`
			LogInv      *int    `json:"log_inv,omitempty"`
			Title       *string `json:"title,omitempty"`
			Created     *string `json:"created,omitempty"`
			Updated     *string `json:"updated,omitempty"`
			Type        *string `json:"type,omitempty"`
			Status      *string `json:"status,omitempty"`
			Attachment  *string `json:"attachment,omitempty"`
			DeliveryFee *int    `json:"delivery_fee,omitempty"`
			Info        *string `json:"info,omitempty"`
		} `json:"awb,omitempty"`
		Complaint *struct {
			ID           *int    `json:"id,omitempty"`
			LogType      *int    `json:"log_type,omitempty"`
			NewLogID     *int    `json:"new_log_id,omitempty"`
			NewInboundID *int    `json:"new_inbound_id,omitempty"`
			TicketID     *int    `json:"ticket_id,omitempty"`
			Type         *string `json:"type,omitempty"`
			Status       *string `json:"status,omitempty"`
			Message      *string `json:"message,omitempty"`
			Picture      *string `json:"picture,omitempty"`
			PictureThumb *string `json:"picture_thumb,omitempty"`
			Video        *string `json:"video,omitempty"`
			Created      *string `json:"created,omitempty"`
			Updated      *string `json:"updated,omitempty"`
		} `json:"compla*int,omitempty"`
		Retur *struct {
			ID          *int    `json:"id,omitempty"`
			Created     *string `json:"created,omitempty"`
			Updated     *string `json:"updated,omitempty"`
			Type        *string `json:"type,omitempty"`
			Status      *string `json:"status,omitempty"`
			Fee         *int    `json:"fee,omitempty"`
			FeeOwner    *int    `json:"fee_owner,omitempty"`
			DeliveryFee *int    `json:"delivery_fee,omitempty"`
			Message     *string `json:"message,omitempty"`
			Resi        *string `json:"resi,omitempty"`
			Platform    *string `json:"platform,omitempty"`
			PickingTs   *string `json:"picking_ts,omitempty"`
			PackingTs   *string `json:"packing_ts,omitempty"`
			ShippingTs  *string `json:"shipping_ts,omitempty"`
			DoneTs      *string `json:"done_ts,omitempty"`
			Items       []*struct {
				ID           *int    `json:"id,omitempty"`
				ProductID    *int    `json:"product_id,omitempty"`
				SkuID        *int    `json:"sku_id,omitempty"`
				SkuLabel     *string `json:"sku_label,omitempty"`
				Name         *string `json:"name,omitempty"`
				Qty          *int    `json:"qty,omitempty"`
				Price        *int    `json:"price,omitempty"`
				Picture      *string `json:"picture,omitempty"`
				PictureThumb *string `json:"picture_thumb,omitempty"`
			} `json:"items,omitempty"`
		} `json:"retur,omitempty"`
	} `json:"data,omitempty"`
}
