package s3domain

// Semua yang diubah menjadi interface{} supaya lebih aman untuk sementara
type JsonFile struct {
	Result  int    `json:"result"`
	Message string `json:"message"`
	Data    struct {
		Inv struct {
			ID                  *interface{} `json:"id,omitempty"`
			LogID               *interface{} `json:"log_id,omitempty"`
			MoveID              *interface{} `json:"move_id,omitempty"`
			ExitID              *interface{} `json:"exit_id,omitempty"`
			LogInv              *interface{} `json:"log_inv,omitempty"`
			Title               *interface{} `json:"title,omitempty"`
			Invoice             *interface{} `json:"invoice,omitempty"`
			InvType             *interface{} `json:"inv_type,omitempty"`
			LogDate             *interface{} `json:"log_date,omitempty"`
			LogUpdated          *interface{} `json:"log_updated,omitempty"`
			ExitDate            *interface{} `json:"exit_date,omitempty"`
			ExitUpdated         *interface{} `json:"exit_updated,omitempty"`
			ExitTitle           *interface{} `json:"exit_title,omitempty"`
			ExitType            *interface{} `json:"exit_type,omitempty"`
			ExitRate            *interface{} `json:"exit_rate,omitempty"`
			ExitAwb             *interface{} `json:"exit_awb,omitempty"`
			MoveAwb             *interface{} `json:"move_awb,omitempty"`
			Created             *interface{} `json:"created,omitempty"`
			Updated             *interface{} `json:"updated,omitempty"`
			Warehouse           *interface{} `json:"warehouse,omitempty"`
			Message             *interface{} `json:"message,omitempty"`
			Type                *interface{} `json:"type,omitempty"`
			Status              *interface{} `json:"status,omitempty"`
			Attachment          *string      `json:"attachment,omitempty"`
			Detail              *interface{} `json:"detail,omitempty"`
			Seller              *interface{} `json:"seller,omitempty"`
			SellerName          *interface{} `json:"seller_name,omitempty"`
			SenderName          *interface{} `json:"sender_name,omitempty"`
			SenderPhone         *interface{} `json:"sender_phone,omitempty"`
			SenderPhoto         *interface{} `json:"sender_photo,omitempty"`
			ReceiverName        *string      `json:"receiver_name,omitempty"`
			ReceiverAddr        *interface{} `json:"receiver_addr,omitempty"`
			ReceiverPhone       *interface{} `json:"receiver_phone,omitempty"`
			ReceiverEmail       *interface{} `json:"receiver_email,omitempty"`
			ReceiverLatlon      *interface{} `json:"receiver_latlon,omitempty"`
			Info                *interface{} `json:"info,omitempty"`
			Info1               *interface{} `json:"info1,omitempty"`
			Info2               *interface{} `json:"info2,omitempty"`
			Info3               *interface{} `json:"info3,omitempty"`
			PickupType          *interface{} `json:"pickup_type,omitempty"`
			PickupStatus        *interface{} `json:"pickup_status,omitempty"`
			ReturnStatus        *interface{} `json:"return_status,omitempty"`
			TransactionVal      *interface{} `json:"transaction_val,omitempty"`
			Fee                 *interface{} `json:"fee,omitempty"`
			FeeWarehouse        *interface{} `json:"fee_warehouse,omitempty"`
			BookingCode         *interface{} `json:"booking_code,omitempty"`
			StorageType         *interface{} `json:"storage_type,omitempty"`
			ShowLogo            *interface{} `json:"show_logo,omitempty"`
			PackagingVal        *interface{} `json:"packaging_val,omitempty"`
			PackagingSubs       *interface{} `json:"packaging_subs,omitempty"`
			EstimateShippingFee *interface{} `json:"estimate_shipping_fee,omitempty"`
			ShippingFee         *interface{} `json:"shipping_fee,omitempty"`
			Vehicle             *interface{} `json:"vehicle,omitempty"`
			PerformanceTime     *interface{} `json:"performance_time,omitempty"`
			PerformanceCounting *interface{} `json:"performance_counting,omitempty"` // typo perbaiki nama json menjadi `performance_counting``
			IsLock              *interface{} `json:"is_lock,omitempty"`
			IsPaid              *interface{} `json:"is_paid,omitempty"`
			Marketplace         *interface{} `json:"marketplace,omitempty"`
			Skema               *interface{} `json:"skema,omitempty"`
			TotalSku            *interface{} `json:"total_sku,omitempty"`
			TotalStock          *interface{} `json:"total_stock,omitempty"`
			Rate                *interface{} `json:"rate,omitempty"`
			InvRate             *interface{} `json:"inv_rate,omitempty"`
			LogisticType        *interface{} `json:"logistic_type,omitempty"`
			Barcode             *interface{} `json:"barcode,omitempty"`
			MarketplaceName     *interface{} `json:"marketplace_name,omitempty"`
			Platform            *interface{} `json:"platform,omitempty"`
			PickingTs           *interface{} `json:"picking_ts,omitempty"`
			PackingTs           *interface{} `json:"packing_ts,omitempty"`
			ShippingTs          *interface{} `json:"shipping_ts,omitempty"`
			DoneTs              *interface{} `json:"done_ts,omitempty"`
			IntervalAwb         *interface{} `json:"interval_awb,omitempty"`
			Awb                 *interface{} `json:"awb,omitempty"`
			LogAwb              *interface{} `json:"log_awb,omitempty"`
			OldInv              *interface{} `json:"old_inv,omitempty"`
			From                *interface{} `json:"from,omitempty"`
			To                  *interface{} `json:"to,omitempty"`
			VoucherID           *interface{} `json:"voucher_id,omitempty"`
			Voucher             *struct {
				ID            *interface{} `json:"id,omitempty"`
				Created       *interface{} `json:"created,omitempty"`
				CreatedBy     *interface{} `json:"created_by,omitempty"`
				Vcode         *interface{} `json:"vcode,omitempty"`
				Nominal       *interface{} `json:"nominal,omitempty"`
				From          *interface{} `json:"from,omitempty"`
				To            *interface{} `json:"to,omitempty"`
				Target        *interface{} `json:"target,omitempty"`
				RedeemBy      *interface{} `json:"redeem_by,omitempty"`
				RedeemDate    *interface{} `json:"redeem_date,omitempty"`
				Type          *interface{} `json:"type,omitempty"`
				Vsource       *interface{} `json:"vsource,omitempty"`
				TransactionID *interface{} `json:"transaction_id,omitempty"`
			} `json:"voucher,omitempty"`
			Packets []*struct {
				ID          *interface{} `json:"id,omitempty"`
				Seller      *interface{} `json:"seller,omitempty"`
				LogID       *interface{} `json:"log_id,omitempty"`
				Title       *interface{} `json:"title,omitempty"`
				Status      *interface{} `json:"status,omitempty"`
				ArrivedTime *interface{} `json:"arrived_time,omitempty"`
				Resi        *interface{} `json:"resi,omitempty"`
				Items       []*struct {
					ID         *interface{} `json:"id,omitempty"`
					DropshipID *interface{} `json:"dropship_id,omitempty"`
					Name       *interface{} `json:"name,omitempty"`
					Qty        *interface{} `json:"qty,omitempty"`
				} `json:"items,omitempty"`
			} `json:"packets,omitempty"`
			Exchanged *struct {
				ID    *interface{} `json:"id,omitempty"`
				Type  *interface{} `json:"type,omitempty"`
				Title *interface{} `json:"title,omitempty"`
			} `json:"exchanged,omitempty"`
			DetailFrom *struct {
				ID        *interface{} `json:"id,omitempty"`
				Name      *interface{} `json:"name,omitempty"`
				Photo     *interface{} `json:"photo,omitempty"`
				Kecamatan *interface{} `json:"kecamatan,omitempty"`
				Kelurahan *interface{} `json:"kelurahan,omitempty"`
				City      *interface{} `json:"city,omitempty"`
			} `json:"detail_from,omitempty"`
			DetailTo *struct {
				ID        *interface{} `json:"id,omitempty"`
				Name      *interface{} `json:"name,omitempty"`
				Photo     *interface{} `json:"photo,omitempty"`
				Kecamatan *interface{} `json:"kecamatan,omitempty"`
				Kelurahan *interface{} `json:"kelurahan,omitempty"`
				City      *interface{} `json:"city,omitempty"`
			} `json:"detail_to,omitempty"`
			Logistic *struct {
				ID          *interface{} `json:"id,omitempty"`
				Name        *interface{} `json:"name,omitempty"`
				Icon        *interface{} `json:"icon,omitempty"`
				Type        *interface{} `json:"type,omitempty"`
				Active      *interface{} `json:"active,omitempty"`
				Cashless    *interface{} `json:"cashless,omitempty"`
				BookingType *interface{} `json:"booking_type,omitempty"`
				PickupType  *interface{} `json:"pickup_type,omitempty"`
				Company     *interface{} `json:"company,omitempty"`
			} `json:"logistic,omitempty"`
			Packaging []*struct {
				PackagingID         *interface{} `json:"packaging_id,omitempty"`
				PackagingName       *interface{} `json:"packaging_name,omitempty"`
				PackagingUnit       *interface{} `json:"packaging_unit,omitempty"`
				PackagingPrice      *interface{} `json:"packaging_price,omitempty"`
				PackagingImage      *interface{} `json:"packaging_image,omitempty"`
				PackagingImageThumb *interface{} `json:"packaging_image_thumb,omitempty"`
				Qty                 *interface{} `json:"qty,omitempty"`
				Total               *interface{} `json:"total,omitempty"`
			} `json:"packaging,omitempty"`
			Items []*struct {
				ID               *interface{} `json:"id,omitempty"`
				Sku              *interface{} `json:"sku,omitempty"`
				Seller           *interface{} `json:"seller,omitempty"`
				SellerName       *interface{} `json:"seller_name,omitempty"`
				ProductID        *interface{} `json:"product_id,omitempty"`
				SkuID            *interface{} `json:"sku_id,omitempty"`
				SkuLabel         *interface{} `json:"sku_label,omitempty"`
				Name             *interface{} `json:"name,omitempty"`
				Qty              *interface{} `json:"qty,omitempty"`
				Price            *interface{} `json:"price,omitempty"`
				Picture          *interface{} `json:"picture,omitempty"`
				PictureThumb     *interface{} `json:"picture_thumb,omitempty"`
				Qc               *interface{} `json:"qc,omitempty"`
				QcFlag           *interface{} `json:"qc_flag,omitempty"`
				QcStatus         *interface{} `json:"qc_status,omitempty"`
				QcPass           *interface{} `json:"qc_pass,omitempty"`
				ExpiredFlag      *interface{} `json:"expired_flag,omitempty"`
				VariantFirstLvl  *interface{} `json:"variant_first_lvl,omitempty"`
				VariantSecondLvl *interface{} `json:"variant_second_lvl,omitempty"`
				BinPicked        []*struct {
					BinID *interface{} `json:"bin_id,omitempty"`
					Qty   *interface{} `json:"qty,omitempty"`
					Name  *interface{} `json:"name,omitempty"`
				} `json:"bin_picked,omitempty"`
				Packages []*struct {
					ID         *interface{} `json:"id,omitempty"`
					Name       *interface{} `json:"name,omitempty"`
					Unit       *interface{} `json:"unit,omitempty"`
					Price      *interface{} `json:"price,omitempty"`
					Image      *interface{} `json:"image,omitempty"`
					ImageThumb *interface{} `json:"image_thumb,omitempty"`
					Qty        *interface{} `json:"qty,omitempty"`
					Total      *interface{} `json:"total,omitempty"`
				}
			} `json:"items,omitempty"`
		} `json:"inv,omitempty"`
		Awb *struct {
			ID          *interface{} `json:"id,omitempty"`
			LogInv      *interface{} `json:"log_inv,omitempty"`
			Title       *interface{} `json:"title,omitempty"`
			Created     *interface{} `json:"created,omitempty"`
			Updated     *interface{} `json:"updated,omitempty"`
			Type        *interface{} `json:"type,omitempty"`
			Status      *interface{} `json:"status,omitempty"`
			Attachment  *interface{} `json:"attachment,omitempty"`
			DeliveryFee *interface{} `json:"delivery_fee,omitempty"`
			Info        *interface{} `json:"info,omitempty"`
		} `json:"awb,omitempty"`
		Complaint *struct {
			ID           *interface{} `json:"id,omitempty"`
			LogType      *interface{} `json:"log_type,omitempty"`
			NewLogID     *interface{} `json:"new_log_id,omitempty"`
			NewInboundID *interface{} `json:"new_inbound_id,omitempty"`
			TicketID     *interface{} `json:"ticket_id,omitempty"`
			Type         *interface{} `json:"type,omitempty"`
			Status       *interface{} `json:"status,omitempty"`
			Message      *interface{} `json:"message,omitempty"`
			Picture      *interface{} `json:"picture,omitempty"`
			PictureThumb *interface{} `json:"picture_thumb,omitempty"`
			Video        *interface{} `json:"video,omitempty"`
			Created      *interface{} `json:"created,omitempty"`
			Updated      *interface{} `json:"updated,omitempty"`
		} `json:"compla*interface{},omitempty"`
		Retur *struct {
			ID          *interface{} `json:"id,omitempty"`
			Created     *interface{} `json:"created,omitempty"`
			Updated     *interface{} `json:"updated,omitempty"`
			Type        *interface{} `json:"type,omitempty"`
			Status      *interface{} `json:"status,omitempty"`
			Fee         *interface{} `json:"fee,omitempty"`
			FeeOwner    *interface{} `json:"fee_owner,omitempty"`
			DeliveryFee *interface{} `json:"delivery_fee,omitempty"`
			Message     *interface{} `json:"message,omitempty"`
			Resi        *interface{} `json:"resi,omitempty"`
			Platform    *interface{} `json:"platform,omitempty"`
			PickingTs   *interface{} `json:"picking_ts,omitempty"`
			PackingTs   *interface{} `json:"packing_ts,omitempty"`
			ShippingTs  *interface{} `json:"shipping_ts,omitempty"`
			DoneTs      *interface{} `json:"done_ts,omitempty"`
			Items       []*struct {
				ID           *interface{} `json:"id,omitempty"`
				ProductID    *interface{} `json:"product_id,omitempty"`
				SkuID        *interface{} `json:"sku_id,omitempty"`
				SkuLabel     *interface{} `json:"sku_label,omitempty"`
				Name         *interface{} `json:"name,omitempty"`
				Qty          *interface{} `json:"qty,omitempty"`
				Price        *interface{} `json:"price,omitempty"`
				Picture      *interface{} `json:"picture,omitempty"`
				PictureThumb *interface{} `json:"picture_thumb,omitempty"`
			} `json:"items,omitempty"`
		} `json:"retur,omitempty"`
	} `json:"data,omitempty"`
}
